import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { 
  ArrowLeft, 
  FileText, 
  Sparkles, 
  Clock, 
  Download,
  Share2,
  Copy,
  CheckCircle,
  Lightbulb,
  Target,
  BookOpen
} from 'lucide-react'
import { motion } from 'framer-motion'
import { useDocumentStore } from '@/store/documentStore'
import { documentApi, summaryApi } from '@/lib/api'
import { calculateReadingTime } from '@/lib/utils'
import toast from 'react-hot-toast'

export function SummaryPage() {
  const { id } = useParams<{ id: string }>()
  const { 
    currentDocument, 
    currentSummary,
    setCurrentDocument, 
    setCurrentSummary,
    isLoading,
    setLoading,
    error,
    setError
  } = useDocumentStore()

  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (id) {
      loadDocumentAndSummary(id)
    }
  }, [id])

  const loadDocumentAndSummary = async (documentId: string) => {
    setLoading(true)
    setError(null)

    try {
      const [document, summary] = await Promise.all([
        documentApi.getDocument(documentId),
        summaryApi.getSummary(documentId)
      ])
      
      setCurrentDocument(document)
      setCurrentSummary(summary)
    } catch (error) {
      console.error('Failed to load document or summary:', error)
      setError(error instanceof Error ? error.message : 'Failed to load content')
      toast.error('Failed to load summary')
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = async () => {
    if (!currentSummary) return

    try {
      await navigator.clipboard.writeText(currentSummary.content)
      setCopied(true)
      toast.success('Summary copied to clipboard')
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast.error('Failed to copy to clipboard')
    }
  }

  const downloadSummary = () => {
    if (!currentSummary || !currentDocument) return

    const content = `# ${currentDocument.originalName} - AI Summary

Generated on: ${new Date(currentSummary.createdAt).toLocaleDateString()}
Processing time: ${currentSummary.processingTime}s

## Summary
${currentSummary.content}

## Key Points
${currentSummary.keyPoints.map(point => `• ${point}`).join('\n')}

---
Generated by Document Summarizer AI
`

    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${currentDocument.originalName.replace('.pdf', '')}_summary.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-96">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading summary...</p>
        </div>
      </div>
    )
  }

  if (error || !currentDocument || !currentSummary) {
    return (
      <div className="text-center py-12">
        <FileText className="h-12 w-12 text-gray-300 mx-auto mb-4" />
        <h3 className="text-lg font-medium text-gray-900 mb-2">Summary not found</h3>
        <p className="text-gray-500 mb-4">{error || 'The requested summary could not be loaded.'}</p>
        <Link to="/" className="btn-primary">
          Back to Documents
        </Link>
      </div>
    )
  }

  const readingTime = calculateReadingTime(currentSummary.content)

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-4"
      >
        <div className="flex items-center space-x-4">
          <Link
            to={`/document/${currentDocument.id}`}
            className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Document</span>
          </Link>
          <div className="h-6 w-px bg-gray-300" />
          <div className="flex items-center space-x-2">
            <Sparkles className="h-5 w-5 text-gold-500" />
            <span className="text-sm font-medium text-gold-600">AI Generated Summary</span>
          </div>
        </div>

        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              {currentDocument.originalName.replace('.pdf', '')}
            </h1>
            <div className="flex items-center space-x-4 text-sm text-gray-500">
              <span className="flex items-center space-x-1">
                <Clock className="h-4 w-4" />
                <span>{readingTime} min read</span>
              </span>
              <span>•</span>
              <span>Generated in {currentSummary.processingTime}s</span>
              <span>•</span>
              <span>{new Date(currentSummary.createdAt).toLocaleDateString()}</span>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={copyToClipboard}
              className="flex items-center space-x-2 btn-secondary"
            >
              {copied ? (
                <CheckCircle className="h-4 w-4 text-green-500" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>
            <button
              onClick={downloadSummary}
              className="flex items-center space-x-2 btn-secondary"
            >
              <Download className="h-4 w-4" />
              <span>Download</span>
            </button>
            <button className="flex items-center space-x-2 btn-secondary">
              <Share2 className="h-4 w-4" />
              <span>Share</span>
            </button>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="lg:col-span-2 space-y-6"
        >
          {/* Summary Content */}
          <div className="card p-8">
            <div className="flex items-center space-x-2 mb-6">
              <BookOpen className="h-5 w-5 text-primary-500" />
              <h2 className="text-xl font-semibold text-gray-900">Summary</h2>
            </div>
            
            <div className="prose prose-gray max-w-none">
              <div className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {currentSummary.content}
              </div>
            </div>
          </div>

          {/* Key Points */}
          {currentSummary.keyPoints && currentSummary.keyPoints.length > 0 && (
            <div className="card p-8">
              <div className="flex items-center space-x-2 mb-6">
                <Target className="h-5 w-5 text-gold-500" />
                <h2 className="text-xl font-semibold text-gray-900">Key Points</h2>
              </div>
              
              <div className="space-y-4">
                {currentSummary.keyPoints.map((point, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 * index }}
                    className="flex items-start space-x-3 p-4 bg-gold-50 border border-gold-200 rounded-lg"
                  >
                    <div className="w-6 h-6 bg-gold-500 text-white rounded-full flex items-center justify-center text-sm font-medium flex-shrink-0 mt-0.5">
                      {index + 1}
                    </div>
                    <p className="text-gray-700 leading-relaxed">{point}</p>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
        </motion.div>

        {/* Sidebar */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="space-y-6"
        >
          {/* Document Info */}
          <div className="card p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Document Details</h3>
            <div className="space-y-3">
              <div className="flex items-center space-x-3">
                <FileText className="h-4 w-4 text-gray-400" />
                <div>
                  <p className="text-sm font-medium text-gray-900">
                    {currentDocument.originalName}
                  </p>
                  <p className="text-xs text-gray-500">
                    {(currentDocument.fileSize / 1024 / 1024).toFixed(1)} MB
                  </p>
                </div>
              </div>
              
              {currentDocument.pageCount && (
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-500">Pages:</span>
                  <span className="text-gray-900">{currentDocument.pageCount}</span>
                </div>
              )}
              
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Uploaded:</span>
                <span className="text-gray-900">
                  {new Date(currentDocument.uploadedAt).toLocaleDateString()}
                </span>
              </div>
            </div>
            
            <div className="mt-4 pt-4 border-t border-gray-200">
              <Link
                to={`/document/${currentDocument.id}`}
                className="w-full btn-primary text-center"
              >
                View Full Document
              </Link>
            </div>
          </div>

          {/* Summary Stats */}
          <div className="card p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Summary Statistics</h3>
            <div className="space-y-3">
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Reading Time:</span>
                <span className="text-gray-900">{readingTime} minutes</span>
              </div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Processing Time:</span>
                <span className="text-gray-900">{currentSummary.processingTime}s</span>
              </div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Key Points:</span>
                <span className="text-gray-900">{(currentSummary.keyPoints || []).length}</span>
              </div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">Word Count:</span>
                <span className="text-gray-900">
                  {(currentSummary.content || "").split(' ').length}
                </span>
              </div>
            </div>
          </div>

          {/* AI Insights */}
          <div className="card p-6">
            <div className="flex items-center space-x-2 mb-4">
              <Lightbulb className="h-4 w-4 text-gold-500" />
              <h3 className="font-semibold text-gray-900">AI Insights</h3>
            </div>
            <div className="space-y-3 text-sm">
              <div className="p-3 bg-primary-50 border border-primary-200 rounded-lg">
                <p className="text-primary-700">
                  This document appears to be well-structured with clear key points that were easily extractable.
                </p>
              </div>
              <div className="p-3 bg-gold-50 border border-gold-200 rounded-lg">
                <p className="text-gold-700">
                  The summary captures {Math.round(((currentSummary?.content?.length || 0) / ((currentDocument?.textContent?.length) || 1000)) * 100)}% compression ratio while maintaining key information.
                </p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
